# This workflow will install the trcli package and run e2e tests

name: End-To-End Tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tests_e2e/requirements.txt
    - name: Test with pytest
      run: |
        coverage run -m pytest \
          -c ./tests_e2e/pytest.ini \
          -W ignore::pytest.PytestCollectionWarning \
          --md-report --md-report-output=report.md --md-report-color=never \
          tests_e2e || pytest_exit_code=$?
        echo "## :clipboard: Test Results" >> $GITHUB_STEP_SUMMARY
        cat report.md >> $GITHUB_STEP_SUMMARY
        echo "## :bar_chart: Code coverage" >> $GITHUB_STEP_SUMMARY
        coverage report --format markdown >> $GITHUB_STEP_SUMMARY
        if [[ $pytest_exit_code -gt 0 ]]
        then
          echo "::error::Unit tests failed" && exit_code=1
        fi
        exit $exit_code
